### ISSUE TITLE
Support for other tagging schemes.

### ISSUE THREAD

**Issue by huyderman** [manuelbua/gitver#20]
`gitver` currently expects version tags to be in the form `vX.Y.Z`. Another common scheme used by some projects is simply `X.Y.Z`. Extending `gitver` to support additional tagging schemes would make it easier to use `gitver` with legacy projects.

**Comment by manuelbua** [comment]
Ahhhh me stupid, that will be in the 0.3.0 as well: for some reason i inadvertedly removed support for this when i've ported it over to Python, nice one :+1:

**Comment by manuelbua** [comment]
I was hoping for `git describe --match=` to use regular expressions, but it's using [glob patterns](https://github.com/git/git/blob/master/builtin/describe.c#L153) instead: have to find another way.. :shit:

**Comment by huyderman** [comment]
Thought I saw some traces of the `X.Y.Z` style being supported while looking through the source code. Good luck finding a workaround. While not essential, it would be a nice-to-have feature.

**Comment by manuelbua** [comment]
Yeah the regex i'm using to check the last tag to be comformant does take the optional "v" into account, but i still need git describe to ensure the hash length is the minimum possible to uniquely describe the commit: i could lazily stick with 8 characters, but i've seen some projects going up to ten chars..
My idea is to still use git-describe to **only** count the number of chars: as of now git-describe's hash is also used for cross-checking and i like it as a form of guarantee, but relaxing that should theoretically permit multiple tag usage.. mmm i'm going to think more about it.

**Comment by manuelbua** [comment]
I've pushed commit 1d170e7, it implements this tag format variation along with some other minor enhancements :satisfied:
