### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by huyderman** [manuelbua/gitver#3]
It would be nice if `gitver` supported the [Semantic Versioning](http://semver.org/) scheme. E.g. `v0.4.10-SNAPSHOT.2+a3a73a5`. Many automated tools support parsing of this scheme, and we use it for many of our projects.

**Comment by manuelbua** [comment]
Good idea, and thanks for the doc: i read that before starting with `gitver` and planned to support custom formats as well to permit exactly this: forcing users to my own version string format wasn't the intention, it's just what i use for the client/server project i'm currently working on.

**Comment by manuelbua** [comment]
This is now implemented in the latest HEAD: you should be able to test it, please let me know, thanks!

**Comment by huyderman** [comment]
Nice. I'll check it out and give it a spin. :)

**Comment by manuelbua** [comment]
Great, let me know if you have trouble installing the dev version, running `./install_dev` for a system-wide installation should be enough.

*removed sudo, it should ask for your password when needed

**Comment by huyderman** [comment]
Had bit problems figuring out how to install, but managed to create a Arch PKGBUILD file to install it system-wide using pacman.

**Comment by manuelbua** [comment]
Hey great! I'm an arch user too!
I should update the docs on building gitver: basically, now you just need to checkout the latest from git, do a `bin/gitver update version` and then you could issue a `python2 setup.py sdist` to create the PyPI distribution package.

**Comment by huyderman** [comment]
If you're interested, here is my current version of a PKGBUILD: https://gist.github.com/huyderman/8420086

It even uses `gitver` to get `pkgver`. :smirk:

It seems to work well enough, but I'm not sure if it's "AUR-ready" yet.

**Comment by manuelbua** [comment]
Cool, thanks!
I'll test it out when i've the time, but it looks great and simple :+1:
A note: with the very latest versions `gitver` comes with its own `.gitver` included, that makes it simpler to checkout and use, so the `gitver init` could be left out.

> It seems to work well enough, but I'm not sure if it's "AUR-ready" yet.

Probably not, but hopefully it will be ready and more stable pretty soon :grinning:

**Comment by manuelbua** [comment]
It looks like custom formatters (and Semantic Versioning) support it's working fine in my dev environment, but i'm interested in your toughts as well, let me know if there are any problems with this, else i'm going to close this issue.

On a completely unrelated note, are you fine for being included in the THANKS file along with your email address? I can't do much against spam, but i'll replace the '@' with a probably useless '[at]' anyway..

**Comment by huyderman** [comment]
No problem. I've had my email plastered on the interwebz for a decade with little or no obfuscation, so I'm not that worried about spam. :smirk:

**Comment by manuelbua** [comment]
Nice, also closing this.
